services:
  web_server:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/inforce_restaurant"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"