# Generated by Django 5.2.5 on 2025-08-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_restaurant_menu_of_the_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="dishes",
            field=models.ManyToManyField(
                related_name="menus", to="restaurant.dish", verbose_name="Dished"
            ),
        ),
    ]
