# Generated by Django 5.2.5 on 2025-08-07 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu_of_the_day',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='featured_in_restaurant', to='restaurant.menu', verbose_name='Menu of the day'),
        ),
    ]
